apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: default
  namespace: backroom
  annotations:
    backstage.io/techdocs-ref: "dir:../../"
spec:
  owner: default/ci
  domain: default/dx
