---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: ci
  description: Constructions Incongrues
  links:
    - url: https://www.constructions-incongrues.net
      title: Website
      icon: public
spec:
  type: organization
  profile:
    displayName: Constructions Incongrues
    email: contact@constructions-incongrues.net
  owner: default/ci
  children: []
