---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: server
  namespace: plesk
spec:
  type: website
  owner: default/constructions-incongrues-net
  system: plesk
  lifecycle: production

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: git
  namespace: plesk
spec:
  type: service
  owner: default/constructions-incongrues-net
  system: plesk
  lifecycle: production
  partOf:
    - component:plesk/server
  dependsOn:
    - component:github/github.com

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storage
  namespace: plesk
spec:
  type: service
  owner: default/constructions-incongrues-net
  system: plesk
  lifecycle: production
  partOf:
    - component:plesk/server

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: database
  namespace: plesk
spec:
  type: database
  owner: default/constructions-incongrues-net
  system: plesk
  lifecycle: production
  partOf:
    - component:plesk/server
